kind: ConfigMap
apiVersion: v1
metadata:
  # Must match the 'spring.application.name' property of the application
  name: application-config
data:
  application.properties: |
    # Override the configuration properties here
    greeting.message=Hello %s from a ConfigMap!
